import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { format } from 'date-fns';

export interface PDFExportOptions {
  title: string;
  subtitle?: string;
  hotelName?: string;
  hotelAddress?: string;
  hotelPhone?: string;
  hotelEmail?: string;
  dateRange?: { start: string; end: string };
  generatedBy?: string;
  currency?: string;
  filename: string;
  headers: string[];
  rows: (string | number)[][];
  summaryRows?: (string | number)[][];
  orientation?: 'portrait' | 'landscape';
  columnStyles?: Record<number, any>;
}

/**
 * Universal utility to export generated data tables as professional, formatted PDF documents.
 * Includes hotel branding header, metadata, elegant autoTable layout, totals, and running page footers.
 */
export function exportTableToPDF(options: PDFExportOptions): void {
  const {
    title,
    subtitle,
    hotelName = 'Hotel Property Management',
    hotelAddress,
    hotelPhone,
    hotelEmail,
    dateRange,
    generatedBy,
    currency,
    filename,
    headers,
    rows,
    summaryRows,
    orientation = headers.length > 6 ? 'landscape' : 'portrait',
    columnStyles
  } = options;

  const doc = new jsPDF({
    orientation,
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Primary brand color: Emerald green #10b981
  const brandEmerald = [16, 185, 129] as [number, number, number];

  // Top header banner band (dark slate)
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 24, 'F');

  // Emerald brand accent line
  doc.setFillColor(16, 185, 129);
  doc.rect(0, 24, pageWidth, 1.5, 'F');

  // Hotel name & title in header
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(hotelName, 14, 11);

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(203, 213, 225);
  const contactParts = [hotelAddress, hotelPhone, hotelEmail].filter(Boolean);
  if (contactParts.length > 0) {
    doc.text(contactParts.join('  |  '), 14, 17);
  } else {
    doc.text('Hotel Property Management System  |  Automated Operational & Financial Record', 14, 17);
  }

  // Right side of top banner: report generation date & currency
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated: ${format(new Date(), 'yyyy-MM-dd HH:mm')}`, pageWidth - 14, 11, { align: 'right' });
  if (currency) {
    doc.text(`Currency: ${currency}`, pageWidth - 14, 17, { align: 'right' });
  }

  // Report Title & Metadata section below banner
  let currentY = 32;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, currentY);

  currentY += 6;
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(71, 85, 105);

  const metaItems: string[] = [];
  if (dateRange?.start && dateRange?.end) {
    metaItems.push(`Period: ${dateRange.start} to ${dateRange.end}`);
  }
  if (subtitle) {
    metaItems.push(subtitle);
  }
  if (generatedBy) {
    metaItems.push(`Generated by: ${generatedBy}`);
  }
  metaItems.push(`Total Records: ${rows.length}`);

  doc.text(metaItems.join('   •   '), 14, currentY);
  currentY += 4;

  // AutoTable configuration
  (doc as any).autoTable({
    startY: currentY,
    head: [headers],
    body: rows,
    foot: summaryRows && summaryRows.length > 0 ? summaryRows : undefined,
    theme: 'grid',
    headStyles: {
      fillColor: brandEmerald,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      cellPadding: 2.2
    },
    footStyles: {
      fillColor: [241, 245, 249],
      textColor: [15, 23, 42],
      fontStyle: 'bold',
      fontSize: 8,
      cellPadding: 2.5
    },
    styles: {
      font: 'helvetica',
      fontSize: 7.5,
      cellPadding: 1.8,
      textColor: [30, 41, 59],
      lineColor: [226, 232, 240],
      lineWidth: 0.1,
      overflow: 'linebreak'
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    columnStyles: columnStyles || {}
  });

  // Stamp running headers/footers on all generated pages after autoTable calculates total page count
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);

    // Top of footer border
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.2);
    doc.line(14, pageHeight - 9, pageWidth - 14, pageHeight - 9);

    doc.text(`${hotelName}  •  Confidential & Proprietary Document`, 14, pageHeight - 5);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 14, pageHeight - 5, { align: 'right' });
  }

  const cleanFilename = filename.endsWith('.pdf') ? filename : `${filename}.pdf`;
  doc.save(cleanFilename);
}
