import { HotelSettings, BookingSource } from './types';

export const DEFAULT_BOOKING_SOURCES: BookingSource[] = [
  { id: 'walk-in', name: 'Walk-in', isActive: true, isDefault: true, order: 0 },
  { id: 'hotel-website', name: 'Hotel Website', isActive: true, isDefault: false, order: 1 },
  { id: 'direct-call', name: 'Direct Call', isActive: true, isDefault: false, order: 2 },
  { id: 'email', name: 'Email', isActive: true, isDefault: false, order: 3 },
  { id: 'corporate', name: 'Corporate', isActive: true, isDefault: false, order: 4 },
  { id: 'travel-agent', name: 'Travel Agent', isActive: true, isDefault: false, order: 5 },
  { id: 'booking-com', name: 'Booking.com', isActive: true, isDefault: false, order: 6 },
  { id: 'agoda', name: 'Agoda', isActive: true, isDefault: false, order: 7 },
  { id: 'expedia', name: 'Expedia', isActive: true, isDefault: false, order: 8 },
  { id: 'airbnb', name: 'Airbnb', isActive: true, isDefault: false, order: 9 },
  { id: 'trip-com', name: 'Trip.com', isActive: true, isDefault: false, order: 10 },
  { id: 'trivago', name: 'Trivago', isActive: true, isDefault: false, order: 11 },
];

export const DEFAULT_SETTINGS: HotelSettings = {
  checkout: {
    allowBalanceOutstanding: false,
    preventOwingGuestCheckout: true,
    requireApprovalForDebtCheckout: true,
    autoMarkUnpaidAsDebt: false,
    allowPartialPaymentCheckout: true,
    requireFullPaymentBeforeCheckout: false,
    allowPostpaidCheckout: false,
    enableUnpaidWarningPopup: true,
    autoGenerateOutstandingInvoice: true,
    gracePeriod: 15,
    lockInvoicesAfterCheckout: true,
  },
  reservations: {
    allowEditing: true,
    allowCancellation: true,
    allowConfirmation: true,
    allowNoShow: true,
    preventOverbooking: true,
    allowDoubleBookingOverride: false,
    requireApprovalForEdits: false,
    autoReleaseNoShow: true,
    autoCancelUnpaidTimeMinutes: 60,
    allowWalkIn: true,
    bookingSources: DEFAULT_BOOKING_SOURCES,
    defaultBookingSourceId: 'walk-in',
  },
  roomBlocking: {
    allowBlocking: true,
    allowUnblocking: true,
    allowRecurringBlocks: false,
    allowMaintenanceBlocks: true,
    allowHousekeepingBlocks: true,
    allowPartialDayBlocks: false,
    requireReasonForBlock: true,
    preventBookingBlocked: true,
    autoExpireTempBlocks: true,
    maxBlockDuration: 30,
  },
  financial: {
    allowRefunds: true,
    requireApprovalForRefunds: true,
    allowDiscounts: true,
    requireApprovalForLargeDiscounts: true,
    largeDiscountThreshold: 10,
    allowManualLedgerAdjustments: false,
    allowExpenseManagement: true,
    allowFinancialReportViewing: true,
    allowExportingReports: true,
    allowInvoiceEditingAfterPayment: false,
    lockInvoicesAfterCheckout: true,
  },
  payments: {
    allowSplitPayments: true,
    allowMultipleMethods: true,
    allowOfflinePayments: true,
    requireTransactionReference: true,
    requirePaymentProofUpload: false,
    allowPaymentReversal: false,
    trackPaymentStaff: true,
    autoSendReceipts: true,
  },
  guests: {
    allowProfileEditing: true,
    allowDeletion: false,
    allowBlacklisting: true,
    allowLoyaltyEditing: true,
    allowEmailCommunication: true,
    allowHistoryViewing: true,
    requireIdVerification: false,
    requirePhoneVerification: false,
  },
  checkIn: {
    allowEarlyCheckIn: true,
    requireRoomInspection: true,
    preventCheckInDirty: true,
    preventCheckInMaintenance: true,
    allowManualRoomOverride: false,
    requirePaymentBeforeCheckIn: false,
    allowCheckInPendingBalance: true,
  },
  housekeeping: {
    allowStatusUpdates: true,
    allowDirtyToCleanChanges: true,
    requireConfirmationForAvailability: true,
    preventOccupiedOverride: true,
    autoSyncStatusAfterCheckout: true,
  },
  staff: {
    allowActivityTracking: true,
    allowSessionMonitoring: false,
    restrictByDepartment: false,
    enableRoleInheritance: true,
  },
  auditLogs: {
    enableFullLogging: true,
    trackReservations: true,
    trackPayments: true,
    trackRoomChanges: true,
    trackAuthEvents: true,
    trackDeletions: true,
    restrictLogVisibility: true,
  },
  reporting: {
    allowExports: true,
    allowScheduledReports: false,
    allowFiltering: true,
    allowRevenueAnalytics: true,
    allowOccupancyAnalytics: true,
    restrictSensitiveReports: true,
  },
  notifications: {
    sendReservationAlerts: true,
    sendPaymentAlerts: true,
    sendNoShowAlerts: true,
    sendMaintenanceAlerts: true,
    sendOverduePaymentAlerts: true,
    sendRoomStatusAlerts: true,
    enableEmail: true,
    enableSms: false,
    enableLowBalanceAlerts: true,
    lowBalanceAlertRoles: ['hotelAdmin', 'manager', 'accountant'],
    lowBalanceAlertMinorDips: false,
  },
  security: {
    require2FAForAdmins: false,
    forcePasswordResetDays: 0,
    sessionTimeoutMinutes: 30,
    enableIpTracking: true,
    restrictMultipleLogins: false,
    lockAccountAfterFailedAttempts: 5,
    requireApprovalForSensitiveActions: true,
  }
};
