import { HotelSettings } from './types';

export const DEFAULT_SETTINGS: HotelSettings = {
  checkout: {
    allowBalanceOutstanding: false,
    preventOwingGuestCheckout: true,
    requireApprovalForDebtCheckout: true,
    autoMarkUnpaidAsDebt: false,
    allowPartialPaymentCheckout: true,
    requireFullPaymentBeforeCheckout: false,
    allowPostpaidCheckout: false,
    enableUnpaidWarningPopup: true,
    autoGenerateOutstandingInvoice: true,
    gracePeriod: 15,
  },
  reservations: {
    allowEditing: true,
    allowCancellation: true,
    allowConfirmation: true,
    allowNoShow: true,
    preventOverbooking: true,
    allowDoubleBookingOverride: false,
    requireApprovalForEdits: false,
    autoReleaseNoShow: true,
    autoCancelUnpaidTimeMinutes: 60,
    allowWalkIn: true,
  },
  roomBlocking: {
    allowBlocking: true,
    allowUnblocking: true,
    allowRecurringBlocks: false,
    allowMaintenanceBlocks: true,
    allowHousekeepingBlocks: true,
    allowPartialDayBlocks: false,
    requireReasonForBlock: true,
    preventBookingBlocked: true,
    autoExpireTempBlocks: true,
  },
  financial: {
    allowRefunds: true,
    requireApprovalForRefunds: true,
    allowDiscounts: true,
    requireApprovalForLargeDiscounts: true,
    largeDiscountThreshold: 10,
    allowManualLedgerAdjustments: false,
    allowExpenseManagement: true,
    allowFinancialReportViewing: true,
    allowExportingReports: true,
    allowInvoiceEditingAfterPayment: false,
    lockInvoicesAfterCheckout: true,
  },
  payments: {
    allowSplitPayments: true,
    allowMultipleMethods: true,
    allowOfflinePayments: true,
    requireTransactionReference: true,
    requirePaymentProofUpload: false,
    allowPaymentReversal: false,
    trackPaymentStaff: true,
    autoSendReceipts: true,
  },
  guests: {
    allowProfileEditing: true,
    allowDeletion: false,
    allowBlacklisting: true,
    allowLoyaltyEditing: true,
    allowEmailCommunication: true,
    allowHistoryViewing: true,
    requireIdVerification: false,
    requirePhoneVerification: false,
  },
  checkIn: {
    allowEarlyCheckIn: true,
    requireRoomInspection: true,
    preventCheckInDirty: true,
    preventCheckInMaintenance: true,
    allowManualRoomOverride: false,
    requirePaymentBeforeCheckIn: false,
    allowCheckInPendingBalance: true,
  },
  housekeeping: {
    allowStatusUpdates: true,
    allowDirtyToCleanChanges: true,
    requireConfirmationForAvailability: true,
    preventOccupiedOverride: true,
    autoSyncStatusAfterCheckout: true,
  },
  staff: {
    allowActivityTracking: true,
    allowSessionMonitoring: false,
    restrictByDepartment: false,
    enableRoleInheritance: true,
  },
  auditLogs: {
    enableFullLogging: true,
    trackReservations: true,
    trackPayments: true,
    trackRoomChanges: true,
    trackAuthEvents: true,
    trackDeletions: true,
    restrictLogVisibility: true,
  },
  reporting: {
    allowExports: true,
    allowScheduledReports: false,
    allowFiltering: true,
    allowRevenueAnalytics: true,
    allowOccupancyAnalytics: true,
    restrictSensitiveReports: true,
  },
  notifications: {
    sendReservationAlerts: true,
    sendPaymentAlerts: true,
    sendNoShowAlerts: true,
    sendMaintenanceAlerts: true,
    sendOverduePaymentAlerts: true,
    sendRoomStatusAlerts: true,
    enableEmail: true,
    enableSms: false,
  },
  security: {
    require2FAForAdmins: false,
    forcePasswordResetDays: 0,
    sessionTimeoutMinutes: 30,
    enableIpTracking: true,
    restrictMultipleLogins: false,
    lockAccountAfterFailedAttempts: 5,
    requireApprovalForSensitiveActions: true,
  }
};
